server:
  port: 44000
spring:
  application:
    name: test-rabbitmq-producer
  rabbitmq:
    host: 192.168.3.110
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    connection-timeout: 100000